FROM ghcr.io/astral-sh/uv:0.8.17-python3.10-bookworm-slim

# Java is required for PySpark
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# RUN uv venv && uv pip install pytest pyspark==3.5.6
RUN uv init && \
    uv add pytest pyspark==3.5.6 && \
    uv sync

ENV PYSPARK_PYTHON=.venv/bin/python
ENV SPARK_VERSION=3.5.6

COPY tests/ /app/tests/

CMD ["uv", "run", ".venv/bin/pytest", "--durations=0", "--verbose", "/app/tests/"]
