FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
#FROM ghcr.io/astral-sh/uv:0.8.17-python3.10-bookworm-slim

# Java is required for PySpark
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV SPARK_VERSION=3.5.6
ENV PYSPARK_PYTHON=.venv/bin/python

# RUN uv venv && uv pip install pytest pyspark==3.5.6
RUN uv init && \
    uv add pytest pyspark==${SPARK_VERSION} && \
    uv sync

COPY tests/ tests/

CMD ["uv", "run", ".venv/bin/pytest", "--durations=0", "--verbose", "tests/"]
